
name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: |
          touch .env
          echo MONGO_DB_PATH="${{ secrets.MONGO_DB_PATH }}" >> .env
          echo NODE_ENV=${{ secrets.NODE_ENV }} >> .env
          echo PORT=${{ secrets.PORT }} >> .env
          echo TEST_PORT=${{ secrets.TEST_PORT }} >> .env
          cat .env
      - run: npm install --also=dev
      - run: npm run build --if-present
      - run: npm test
