# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  create-envfile:
    runs-on: self-hosted

    steps:
      - name: Make envfile
        run: |
          touch .env
          echo MONGO_DB_PATH: ${{ secrets.MONGO_DB_PATH }}
          echo NODE_ENV: ${{ secrets.NODE_ENV }}
          echo PORT: ${{ secrets.PORT }}
          echo TEST_PORT: ${{ secrets.TEST_PORT }}
          cat .env

  build:
    runs-on: self-hosted
    needs: create-envfile

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm install --also=dev
      - run: npm run build --if-present
      - run: npm test
